"""
Demo script for LLM Ensemble with Z3 Pre-Check (Phase 1)
"""
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from src.llm_ensemble.ensemble_manager import LLMEnsembleManager
from config.settings import settings

def demo_basic_ensemble():
    """Demonstrate basic ensemble generation"""
    
    print("=" * 70)
    print("DEMO: LLM Ensemble with Z3 Pre-Check (Phase 1)")
    print("=" * 70)
    
    # Create ensemble manager
    print("\n1. Initializing LLM Ensemble Manager...")
    ensemble = LLMEnsembleManager()
    
    # Test requirement
    requirement = "The drone must maintain an altitude between 40 meters and 60 meters inclusive."
    safety_property = "And(altitude >= 40, altitude <= 60)"
    variables = {"altitude": "real"}
    
    print(f"\n2. Requirement: {requirement}")
    print(f"   Safety Property (Z3): {safety_property}")
    print(f"   Variables: {variables}")
    
    # Generate ensemble
    print("\n3. Generating code with ensemble (parallel)...")
    candidates = ensemble.generate_ensemble(
        requirement=requirement,
        safety_property=safety_property,
        variables=variables,
        safety_level="SIL3",
        use_parallel=True
    )
    
    print(f"\n4. Generated {len(candidates)} candidates:")
    print("-" * 50)
    
    for i, candidate in enumerate(candidates, 1):
        print(f"\nCandidate {i}:")
        print(f"  Model: {candidate['model']}")
        print(f"  Z3 Score: {candidate.get('z3_score', 0):.3f}")
        print(f"  Diagnostic: {candidate.get('z3_diagnostic', 'N/A')}")
        print(f"  Generation Time: {candidate.get('generation_time', 0):.2f}s")
        print(f"  Success: {candidate.get('success', False)}")
        
        # Show first few lines of code
        code_preview = candidate['code'][:150] + "..." if len(candidate['code']) > 150 else candidate['code']
        print(f"  Code Preview: {code_preview}")
    
    # Select best candidate
    print("\n5. Selecting best candidate...")
    best = ensemble.select_best_candidate(candidates)
    
    print(f"\n✅ SELECTED CANDIDATE:")
    print(f"   Model: {best['model']}")
    print(f"   Z3 Score: {best.get('z3_score', 0):.3f}")
    print(f"\n   Generated Code:")
    print("-" * 40)
    print(best['code'])
    print("-" * 40)
    
    # Show ensemble statistics
    print("\n6. Ensemble Statistics:")
    stats = ensemble.get_stats()
    print(f"   Total Models: {stats['total_models']}")
    for model_name, model_stats in stats['models'].items():
        print(f"   {model_name}:")
        print(f"     Requests: {model_stats.get('requests', 0)}")
        print(f"     Tokens: {model_stats.get('tokens', 0)}")
        print(f"     Success Rate: {model_stats.get('success_rate', 0):.1%}")
    
    return best

def demo_refinement_loop():
    """Demonstrate refinement with feedback"""
    
    print("\n" + "=" * 70)
    print("DEMO: Refinement Loop with Feedback")
    print("=" * 70)
    
    ensemble = LLMEnsembleManager()
    
    # Initial requirement
    requirement = "The drone's speed must not exceed 10 m/s when obstacle is within 20 meters."
    safety_property = "Implies(distance < 20, speed <= 10)"
    variables = {"speed": "real", "distance": "real"}
    
    print(f"\nRequirement: {requirement}")
    
    # First generation
    print("\n📝 First Generation (might have errors)...")
    candidates = ensemble.generate_ensemble(requirement, safety_property, variables)
    first_best = ensemble.select_best_candidate(candidates)
    
    print(f"Generated by: {first_best['model']}")
    print(f"Z3 Score: {first_best.get('z3_score', 0):.3f}")
    print(f"\nCode:\n{first_best['code']}")
    
    # Simulate finding an error
    print("\n⚠️  Found error: Code doesn't handle distance >= 20 case properly")
    previous_error = "Counterexample: distance=25, speed=15 (should be safe but code returns False)"
    
    # Refinement generation
    print("\n🔄 Refinement Generation (with feedback)...")
    refined = ensemble.generate_with_feedback(
        requirement=requirement,
        safety_property=safety_property,
        variables=variables,
        previous_error=previous_error
    )
    
    print(f"Refined by: {refined['model']}")
    print(f"Z3 Score: {refined.get('z3_score', 0):.3f}")
    print(f"\nRefined Code:\n{refined['code']}")

def main():
    """Main demo function"""
    
    print("Neuro-Symbolic UAV Framework - Phase 1 Demo")
    print("LLM Ensemble with Z3 Pre-Check")
    print("=" * 70)
    
    try:
        # Demo 1: Basic ensemble
        best_candidate = demo_basic_ensemble()
        
        # Demo 2: Refinement loop
        demo_refinement_loop()
        
        print("\n" + "=" * 70)
        print("✅ Phase 1 Implementation Complete!")
        print("=" * 70)
        print("\nKey Components Implemented:")
        print("1. ✅ Base LLM Client architecture")
        print("2. ✅ Gemini 2.5 Flash integration")
        print("3. ✅ Llama 3.1 70B integration")
        print("4. ✅ Z3 Pre-Check selection")
        print("5. ✅ Ensemble manager with parallel generation")
        print("6. ✅ Prompt strategies for safety-critical code")
        print("7. ✅ Refinement loop with feedback")
        
    except Exception as e:
        print(f"\n❌ Demo failed with error: {e}")
        import traceback
        traceback.print_exc()
        return 1
    
    return 0

if __name__ == "__main__":
    sys.exit(main())